// <auto-generated />
namespace LMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class seedandroles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seedandroles));
        
        string IMigrationMetadata.Id
        {
            get { return "201803071354323_seed and roles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
